import { Product, Category, User } from '@/types';

// Sample Categories
export const categories: Category[] = [
  {
    id: '1',
    name: 'Pesticide Sprayer Pumps',
    slug: 'pesticide-sprayers',
    description: 'High-quality pesticide sprayer pumps for effective crop protection',
  },
  {
    id: '2',
    name: 'Battery Sprayers',
    slug: 'battery-sprayers',
    description: 'Cordless battery-operated sprayers for convenient application',
  },
  {
    id: '3',
    name: 'Manual Sprayers',
    slug: 'manual-sprayers',
    description: 'Reliable manual sprayers for small to medium-sized farms',
  },
  {
    id: '4',
    name: 'Agricultural Equipment',
    slug: 'agricultural-equipment',
    description: 'Essential farming tools and equipment',
  },
  {
    id: '5',
    name: 'Spare Parts & Accessories',
    slug: 'spare-parts',
    description: 'Replacement parts and accessories for your equipment',
  },
  {
    id: '6',
    name: 'Other Farming Products',
    slug: 'other-products',
    description: 'Various other agricultural products',
  },
];

// Sample Products
export const products: Product[] = [
  {
    id: '1',
    name: 'Professional Knapsack Sprayer - 16L',
    category: 'Pesticide Sprayers',
    price: 2499,
    originalPrice: 3499,
    description:
      'High-capacity knapsack sprayer with brass pump and ergonomic design. Perfect for agricultural pesticide and fertilizer application.',
    specifications: {
      capacity: '16 Liters',
      material: 'Plastic with brass fittings',
      warranty: '2 years',
      pumpType: 'Brass pump with high pressure',
      sprayPattern: 'Adjustable from mist to jet',
      weight: '2.5 kg (empty)',
    },
    features: [
      'High-quality brass pump for durability',
      'Adjustable spray pressure',
      'Comfortable shoulder straps',
      'Chemical-resistant plastic tank',
      'Easy to maintain and clean',
      'Suitable for pesticides and fertilizers',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 45,
    sku: 'KS-16L-001',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '2',
    name: 'Battery Powered Sprayer - 12V 8L',
    category: 'Battery Sprayers',
    price: 4999,
    originalPrice: 6499,
    description:
      'Efficient battery-powered sprayer with 12V rechargeable battery. Ideal for quick and effortless crop spraying.',
    specifications: {
      capacity: '8 Liters',
      battery: '12V lithium-ion rechargeable',
      runtime: '3-4 hours per charge',
      material: 'Stainless steel + plastic',
      pressure: '2-3 bar',
      weight: '3.2 kg (with battery)',
    },
    features: [
      'Cordless operation with 12V battery',
      'Adjustable pressure control',
      'Lightweight and easy to handle',
      'Water-resistant design',
      'Includes battery and charger',
      'Reduces manual effort by 80%',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 28,
    sku: 'BS-12V-001',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '3',
    name: 'Manual Trigger Sprayer - 5L',
    category: 'Manual Sprayers',
    price: 599,
    description:
      'Compact manual trigger sprayer perfect for small gardens and household use. Lightweight and easy to operate.',
    specifications: {
      capacity: '5 Liters',
      material: 'Plastic with rubber trigger',
      nozzleType: 'Adjustable nozzle',
      warranty: '1 year',
      weight: '0.8 kg',
    },
    features: [
      'Lightweight and portable',
      'Adjustable spray settings',
      'Ergonomic trigger handle',
      'Suitable for various liquids',
      'Easy to refill and clean',
      'Affordable and reliable',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 120,
    sku: 'TS-5L-001',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '4',
    name: 'Heavy-Duty Rotary Sprayer Pump',
    category: 'Pesticide Sprayers',
    price: 8999,
    originalPrice: 11999,
    description:
      'Commercial-grade rotary sprayer pump designed for large-scale agricultural operations. Powerful and efficient.',
    specifications: {
      capacity: '20 Liters',
      engine: 'Petrol-powered 2-stroke',
      pressure: '50 bar',
      spraying: 'Fast and consistent',
      warranty: '3 years',
      weight: '12 kg',
    },
    features: [
      'High-pressure output for deep coverage',
      'Durable petrol-powered engine',
      'Ideal for large farm areas',
      'Built for commercial use',
      'Weather-resistant construction',
      'Extended warranty and support',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 12,
    sku: 'RP-20L-001',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '5',
    name: 'Brass Pump Assembly Kit',
    category: 'Spare Parts & Accessories',
    price: 1299,
    description: 'Replacement brass pump assembly for various sprayer models. High-quality and durable.',
    specifications: {
      material: 'Solid brass',
      compatibility: 'Most standard sprayers',
      warranty: '2 years',
      weight: '0.6 kg',
    },
    features: [
      'High-quality brass construction',
      'Easy installation',
      'Compatible with multiple models',
      'Long-lasting performance',
      'Comes with mounting hardware',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 85,
    sku: 'PK-BRASS-001',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '6',
    name: 'Agricultural Hose Assembly - 10M',
    category: 'Spare Parts & Accessories',
    price: 799,
    description: 'Durable agricultural hose with brass fittings. Resistant to chemicals and UV rays.',
    specifications: {
      length: '10 meters',
      diameter: '1/2 inch',
      material: 'Reinforced rubber',
      pressure: '10 bar rated',
      weight: '1.8 kg',
    },
    features: [
      'Chemical-resistant rubber',
      'UV-resistant material',
      'Brass end fittings',
      'Flexible and durable',
      'Easy to connect and disconnect',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 50,
    sku: 'HOSE-10M-001',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '7',
    name: 'Organic Pesticide Concentrate',
    category: 'Other Farming Products',
    price: 449,
    description:
      'Bio-pesticide concentrate made from natural ingredients. Safe for crops and environment.',
    specifications: {
      volume: '500 ML',
      concentration: '100% natural',
      shelfLife: '2 years',
      phLevel: 'Neutral',
    },
    features: [
      'Organic and eco-friendly',
      'Safe for use on food crops',
      'Effective against common pests',
      'Long shelf life',
      'Easy to dilute and apply',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 200,
    sku: 'ORG-PEST-001',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '8',
    name: 'Soil Testing Kit',
    category: 'Agricultural Equipment',
    price: 1999,
    description:
      'Complete soil testing kit for checking pH, nutrient content, and soil quality.',
    specifications: {
      components: '5 test strips',
      accuracy: '±0.5 pH',
      testTypes: 'NPK, pH, Moisture',
      warranty: '1 year',
    },
    features: [
      'Easy to use',
      'Accurate results',
      'Comprehensive testing',
      'Portable kit',
      'Includes instruction manual',
      'Saves on lab testing costs',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 35,
    sku: 'SK-TEST-001',
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: '9',
    name: 'Drip Irrigation Kit - 100M',
    category: 'Agricultural Equipment',
    price: 3499,
    originalPrice: 4499,
    description:
      'Complete drip irrigation system for efficient water management in agriculture.',
    specifications: {
      coverage: '100 square meters',
      components: 'Pipes, drippers, filters, connectors',
      waterUsage: 'Saves up to 70% water',
      warranty: '3 years',
    },
    features: [
      'Water-efficient drip system',
      'Easy installation',
      'Uniform water distribution',
      'Reduces labor costs',
      'Compatible with most soils',
      'Eco-friendly solution',
    ],
    images: [
      'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=500',
    quantity: 20,
    sku: 'DRI-KIT-100',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-09-01'),
  },
];

// Sample Users (Demo accounts)
export const users: User[] = [
  {
    id: 'user-1',
    email: 'customer@example.com',
    name: 'Rajesh Kumar',
    phone: '+91-9876543210',
    role: 'customer',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-09-01'),
  },
  {
    id: 'user-2',
    email: 'admin@vedhaagro.com',
    name: 'Admin User',
    phone: '+91-9876543211',
    role: 'admin',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-09-01'),
  },
];
